# BEGIN_KITTY_THEME
# Solarized Dark Higher Contrast
include current-theme.conf
# END_KITTY_THEME

# Appearance

## Font
font_family      DejaVuSansM Nerd Font Mono
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size 12.0

## Background
background_opacity 0.92

## Windows
window_margin_width 1

window_border_width 1pt
active_border_color #44ffff
single_window_margin_width 0

## Tabs
tab_bar_edge top
tab_bar_style powerline
tab_powerline_style slanted
tab_title_template "{fmt.fg.c2c2c2}{index}: {title}"

active_tab_title_template "{fmt.fg._fff}{index}: {title}"
active_tab_foreground #fff
active_tab_font_style bold-italic
active_tab_background #004848

inactive_tab_foreground #c2c2c2
inactive_tab_background #002727

## Multiple Windows
enabled_layouts Grid

## Cursor
cursor_shape block
cursor_shape_unfocused hollow
cursor_trail 10
cursor_trail_color #4dff44

## URLs
detect_urls yes
url_style straight
open_url_with default


# Behaviour

## Term Variable
term xterm-kitty

## Shell Integration
shell_integration no-cursor

# Auto Reload Config
auto_reload_config 0.3

## Tab Switching
tab_switch_strategy left

## Copy
copy_on_select yes

## Paste
strip_trailing_spaces smart

## Scrollback
scrollback_lines 5000

## Terminal bell
enable_audio_bell noclear


# Keyboard
macos_option_as_alt yes

## Kitty Fixo (shift+enter for cld)
map shift+enter send_text all \x1b[13;2u

## copy Pasta
map ctrl+v paste_from_clipboard

## Tabs
map ctrl+t new_tab_with_cwd
map ctrl+tab next_tab
map ctrl+shift+tab previous_tab

## Windows
map ctrl+shift+enter launch --cwd=current
map ctrl+shift+q quit # cmd+q is quit, or super+q
map ctrl+w close_window

map ctrl+up neighboring_window top
map ctrl+right neighboring_window right
map ctrl+down neighboring_window bottom
map ctrl+left neighboring_window left

map ctrl+shift+up move_window top
map ctrl+shift+right move_window right
map ctrl+shift+down move_window bottom
map ctrl+shift+left move_window left

# Command Palette
map ctrl+shift+a command_palette
map cmd+shift+a command_palette

# osx specific
macos_titlebar_color #006464
macos_option_as_alt yes
macos_quit_when_last_window_closed yes

# Overrides for this box
include overrides.conf