# Context aware quit for Kitty terminal emulator
map ctrl+w launch --type=background ~/.config/kitty/kitty-aware-quit close_window
map ctrl+q launch --type=background ~/.config/kitty/kitty-aware-quit quit_app