# Context aware quit for Kitty terminal emulator
map cmd+w launch --type=background ~/.config/kitty/kitty-aware-quit close_window
map cmd+q launch --type=background ~/.config/kitty/kitty-aware-quit quit_app