# Linux keys and settings, included from kitty.conf.

enabled_layouts grid,stack

## Copy and paste
map ctrl+v paste_from_clipboard

## Tabs
map ctrl+t new_tab_with_cwd
map ctrl+tab next_tab
map ctrl+shift+tab previous_tab

## Panes
map ctrl+shift+enter launch --cwd=current
map ctrl+shift+q quit
map ctrl+w close_window
# Close the other panes in this tab, or the other tabs if this is the only pane
map ctrl+shift+w kitten close_others.py

map ctrl+up neighboring_window top
map ctrl+right neighboring_window right
map ctrl+down neighboring_window bottom
map ctrl+left neighboring_window left

map ctrl+shift+up move_window top
map ctrl+shift+right move_window right
map ctrl+shift+down move_window bottom
map ctrl+shift+left move_window left

## Command palette
map ctrl+shift+a command_palette
