#!/usr/bin/env zsh


_reshim_description="Runs asdf reshim and fixes shims to avoid collision"
_reshim_flags[1]="--help"
_reshim_flag_descriptions[1]="Prints Help"

shims=('clear' 'tput' 'curl' 'gettext.sh' 'gettext' 'envsubst')

function _asdf_reshim_fix() {
  if is not existing "$ASDF_DIR/shims"; then
    clr_red "ASDF_DIR not found, set ASDF_DIR to the path to .asdf (usually ~/.asdf)"
    return 1
  fi

  for shim in $shims; do
    without_nl=${shim:-1}
    SHIM="$ASDF_DIR/shims/$without_nl"
    if is file "$SHIM"; then
      sudo chmod -x "$SHIM"
      rm -f "$SHIM"
      clr_green "Fixed " -n; clr_white "$without_nl"
    else
      clr_brown "Skipped " -n; clr_white "$without_nl" -n; clr_brown ", does not exist"
    fi
  done
}

# asdf-reshim: Lazy issue mentions in a git commit -m
function asdf-reshim () {
  local DEPS=(
    is
    clr_cyan
    clr_green
    clr_white
    clr_red
    asdf
  )

  if ! deps $DEPS; then
    return
  fi

  if has-flag '--help' $@; then
    print-help $0 "$_reshim_description" "_reshim_flags" "_reshim_flag_descriptions"
    clr_cyan "\nShims:"
    for shim in $shims; do
      echo -n "- "; clr_green "$shim"
    done
    return
  fi

  if is not available "asdf"; then
    clr_brown "Could not find asdf!"
    return 1
  fi

  clr_green "Reshimming " -n; clr_white "ASDF"
  asdf reshim
  RESULT=$?
  if is equal $RESULT 0; then
    clr_green "Reshimmed " -n; clr_white "ASDF"
  else
    clr_brown "Something may have gone wrong, try running " -n
    clr_white "asdf reshim " -n
    clr_brown "manually"
  fi

  _asdf_reshim_fix
}

asdf-reshim "$@"
