#!/usr/bin/env zsh

function asdf-cleanup() {
  if is equal "$1" "--help"; then
    echo "$c[h1]asdf-cleanup$c[reset]"
    echo ""
    echo "$c[lead]removes old versions of asdf plugins, keeping only the globally set version.$c[reset]"
    echo ""
    echo "$c[h2]usage$c[reset]"
    echo "  asdf-cleanup $c[flag][--help]$c[reset]"
    return 0
  fi

  echo "$c[h1]asdf cleanup$c[reset]"
  echo ""
  local global_versions=$(cat ~/.tool-versions)

  for plugin in $(asdf plugin list); do
    echo "$c[h2]$plugin$c[reset]"
    local versions=$(asdf list $plugin 2>/dev/null)
    local no_versions="No compatible versions installed ($plugin)"
    if is equal "$versions" "$no_versions"; then
      echo "$c[error]error:$c[reset] no versions installed — consider removing this plugin"
      echo ""
      continue
    fi

    local global_version=$(echo "$global_versions" | grep "^$plugin " | awk '{print $2}' 2>/dev/null)
    if is not empty "$global_version"; then
      echo "$c[info]keeping:$c[reset] $global_version"
    else
      echo "$c[error]error:$c[reset] no global version set — consider removing this plugin"
      echo ""
      continue
    fi

    local versions_to_remove=()
    for version in ${(f)versions}; do
      if is not substring "$global_version" "$version"; then
        versions_to_remove+=("$version")
      fi
    done

    if is not empty "$versions_to_remove"; then
      for version in $versions_to_remove; do
        echo "$c[info]removing:$c[reset] $version"
        asdf uninstall "$plugin" "$version" 2>/dev/null
        if [[ $? -ne 0 ]]; then
          echo "$c[error]error:$c[reset] failed to remove $version — try 'asdf uninstall $plugin $version' manually"
        fi
      done
    else
      echo "$c[info]skipping:$c[reset] already clean"
    fi

    echo ""
  done
}

asdf-cleanup "$@"
