#!/usr/bin/env zsh


_asdf_reshim_description="Runs asdf reshim and fixes shims to avoid collision"
_asdf_reshim_flags[1]="--help"
_asdf_reshim_flag_descriptions[1]="Prints Help"

shims=('clear' 'tput' 'curl' 'gettext.sh' 'gettext' 'envsubst' 'openssl' 'xz' 'bzip2')

function _asdf_reshim_fix() {
  if is not existing "$ASDF_DATA_DIR/shims"; then
    echo "$ASDF_DATA_DIR/shims $cs[error]not found, check that $c[reset]\$ASDF_DATA_DIR $cs[error]points to the right place.$c[reset]"
    return 1
  fi

  for shim in $shims; do
    without_nl=${shim:-1}
    SHIM="$ASDF_DATA_DIR/shims/$without_nl"
    if is file "$SHIM"; then
      sudo chmod -x "$SHIM"
      rm -f "$SHIM"
      echo "$cs[success]Fixed$c[reset] $without_nl"
    else
      echo "$cs[warn]Skipped$c[reset] $without_nl $cs[warn], does not exist.$c[reset]"
    fi
  done
}

# asdf-reshim: Lazy issue mentions in a git commit -m
function asdf-reshim () {
  local DEPS=(
    is
    asdf
  )

  if ! deps $DEPS; then
    return
  fi

  if has-flag '--help' $@; then
    print-help $0 "$_asdf_reshim_description" "_asdf_reshim_flags" "_asdf_reshim_flag_descriptions"
    echo "\n$cs[h2]Shims:$c[reset]"
    for shim in $shims; do
      echo "- $shim"
    done
    return
  fi

  echo "$cs[h2]Reshimming$c[reset] ASDF"
  asdf reshim
  RESULT=$?
  if is equal $RESULT 0; then
    echo "$cs[h2]Reshimmed$c[reset] ASDF"
  else
    echo "$cs[warn]Something may have gone wrong, try running$c[reset] asdf reshim $cs[warn]manually.$c[reset]"
  fi

  _asdf_reshim_fix
}

asdf-reshim "$@"
