#!/usr/bin/env zsh

_auto_notify_description="Adds a shell command to the list of commands ignored by auto-notify"
_auto_notify_flag_names[1]="--help"
_auto_notify_flag_messages[1]="shows help"
_auto_notify_flag_names[2]="--list"
_auto_notify_flag_messages[2]="lists currently ignored commands"
_auto_notify_flag_names[3]="--add [command]"
_auto_notify_flag_messages[3]="adds [command] to ignored commands"

function _auto-notify-ignore_add() {
  command=$1

  if is not existing "$AUTO_NOTIFY_IGNORE_FILE"; then
    echo "$AUTO_NOTIFY_IGNORE_FILE $cs[error] does not exist, please create it.$c[reset]"
    return
  fi

  echo "AUTO_NOTIFY_IGNORE+=(\"$command\")" >> $AUTO_NOTIFY_IGNORE_FILE
  source $AUTO_NOTIFY_IGNORE_FILE
  echo "$cs[success]Added $c[reset] $command $cs[success]to $c[reset]$AUTO_NOTIFY_IGNORE_FILE"
}

# Lists and adds to AUTO_NOTIFY_IGNORE
# Used by MichaelAquilina/zsh-auto-notify
function auto-notify-ignore () {
  local DEPS=(
    is
    tr
    sort
  )

  if ! deps $DEPS; then
    return
  fi

  if is empty "$1" || has-flag "--help" $@; then
    print-help \
      "$0" \
      "$_auto_notify_description" \
      "_auto_notify_flag_names" \
      "_auto_notify_flag_messages"
    return
  fi

  if has-flag '--add' $@; then
    VALUE=$(flag-value '--add' $@)
    if is empty "$VALUE"; then
      echo "$cs[warn]No command passed to --add, see --help for usage.$c[reset]"
      return 1
    fi

    _auto-notify-ignore_add "$VALUE"
  fi

  if has-flag '--list' $@; then
    echo "$cs[h2]Commands currently ignored:$c[reset]"
    echo $AUTO_NOTIFY_IGNORE | tr ' ' '\n' | sort | uniq
  fi
}

auto-notify-ignore "$@"
