#!/usr/bin/env zsh

function cheat() {
  if [[ -z "$CHEATSHEET_DIR" ]]; then
    echo "CHEATSHEET_DIR not set, set it before running this script"
    return 1
  fi

  if ! command -v glow > /dev/null 2>&1; then
    echo "glow could not be found, please install it before running this script"
    return 1
  fi

  if [[ "$1" != "" ]]; then
    local sheet_name
    sheet_name="${1%.md}"

    if [[ -f "$CHEATSHEET_DIR/$sheet_name.md" ]]; then
      local -a other_args
      other_args=("${(@)argv[2,-1]}")
      if [[ ${#other_args} -gt 0 ]]; then
        glow "$CHEATSHEET_DIR/$sheet_name.md" "${other_args[@]}"
      else
        glow "$CHEATSHEET_DIR/$sheet_name.md"
      fi
    else
      glow "$CHEATSHEET_DIR" "$@"
    fi
  else
    glow "$CHEATSHEET_DIR" "$@"
  fi
}

cheat "$@"
