#!/usr/bin/env zsh

function cheat() {
  if is equal "$1" "--help" ; then
    echo "$c[h1]Personal Cheatsheets$c[reset]"
    echo ""
    echo "$c[h2]Usage:$c[reset]"
    echo "cheat $c[flag][--help]$c[reset] show this help message"
    echo ""
    echo "$c[h3]List all personal cheatsheets$c[reset]"
    echo "cheat $c[flag]--list$c[reset]"
    echo ""
    echo "$c[h3]show specific personal cheatsheet$c[reset]"
    echo "cheat $c[param]sheet-name$c[reset] $c[flag]$c[reset]"
    echo ""
    echo "$c[h3]edit specific personal cheatsheet$c[reset]"
    echo "cheat $c[param]sheet-name$c[reset] $c[flag]--edit$c[reset]"
    echo ""
    return 0
  fi

  if is empty "$CHEATSHEET_DIR"; then
    echo "CHEATSHEET_DIR not set, run zsh-config/install to install it"
    return 1
  fi


  local cheatsheet_command="cat"
  local cheatsheet_command_args=()
  if is available batcat; then
    cheatsheet_command="batcat"
    cheatsheet_command_args=(
      "-p"
      "--color=always"
    )
  fi

  if is empty "$1" || is equal "$1" "--list"; then
    echo "$c[h1]Available Cheatsheets:$c[reset]"
    ls -1 "$CHEATSHEET_DIR" | grep -v '.DS_Store' | sed 's/\.md$//'
    return $?
  fi

  local sheet_name
  sheet_name="${1%.md}"

  if is not file "$CHEATSHEET_DIR/$sheet_name.md"; then
    if is available tldr; then
      tldr "$sheet_name"
      return $?
    else
      echo "Cheatsheet '$sheet_name' not found and tldr is not available"
      return 1
    fi
  fi

  local -a other_args
  other_args=("${(@)argv[2,-1]}")
  if is equal "${#other_args}" "0"; then
    $cheatsheet_command $cheatsheet_command_args "$CHEATSHEET_DIR/$sheet_name.md"
    return $?
  fi

  if is equal "$other_args[1]" "--edit"; then
    $EDITOR "$CHEATSHEET_DIR/$sheet_name.md"
    return $?
  fi
}

cheat "$@"
