#!/usr/bin/env zsh

function _conc_usage() {
  clr_cyan 'Usage:' -n
  clr_white " $1 [Number of iterations] [Number of parallel processes] [command]"
}

# conc: Lazy issue mentions in a git commit -m
function conc () {
  local DEPS=(
    is
    clr_cyan
    clr_green
    clr_white
    clr_red
    git
    current_branch
  )

  if ! deps $DEPS; then
    return
  fi

  if is empty "$1"; then
    _conc_usage "$0"
    return 0
  fi

  if is empty "$2"; then
    _conc_usage "$0"
    return 0
  fi


  cmd=("${@:3}")
  clr_cyan "Running " -n
  clr_white " $1" -n
  clr_cyan " iterations with" -n
  clr_white " $2" -n
  clr_cyan " threads of:"
  clr_green "$cmd"

  seq 1 "$1" | xargs -n1 -P"$2" "${cmd[@]}"
}

conc "$@"
