#!/usr/bin/env zsh

function confirm() {
  MESSAGE=${1:="$cs[warn]Are you sure?$c[reset]"}
  read "confirmed?$MESSAGE $cs[sub][y/n]$c[reset] "
  if [[ "$confirmed" =~ ^[Yy]$ ]]
  then
    return 0
  else
    return 1
  fi
}

confirm "$@"
