#!/usr/bin/env zsh

declare -A steps

steps[asdf]="run zshconfig/install to install asdf"
steps[eza]="$CUSTOM_DIR/installers/eza"
steps[gh]="install github cli: https://cli.github.com/"
steps[http]="run zshconfig/install to install httpie"
steps[python]="asdf plugin add python && asdf install python latest && asdf set -u python latest"

function deps-command() {
  local inst="${steps[$1]}"
  if is not empty "$inst"; then
    echo "$c[info]install:$c[reset] $inst"
  fi
}

function deps() {
  local missing=0

  for dependency in "$@"; do
    if is not available "$dependency"; then
      echo "$c[error]missing dependency:$c[reset] $dependency"
      deps-command "${dependency}"
      missing=1
    fi
  done

  return ${missing}
}

deps "$@"
