#!/usr/bin/env zsh

_fast_download_description="Aria2c wrapper to fast download a URL"
_fast_download_flag_names[1]="--help"
_fast_download_flag_messages[1]="shows help"
_fast_download_flag_names[2]="--directory [directory]"
_fast_download_flag_messages[2]="downloads the file to [directory], if ommitted ~/Downloads is used."

# GCMM: Lazy issue mentions in a git commit -m
function fast-download () {
  local DEPS=(
    is
    aria2c
  )

  if ! deps $DEPS; then
    return
  fi

  if is empty "$1" || has-flag '--help' $@; then
    print-help "$0" "$_fast_download_description" "_fast_download_flag_names" "_fast_download_flag_messages" "url" "The url of the file to download"
    return 0
  fi

  DIRECTORY=~/Downloads
  if has-flag '--directory' $@; then
    DIRECTORY=$(flag-value '--directory' $@)
  fi

  URL="$@[-1]"
  if is empty "$URL"; then
    echo "$cs[error]Could not find url to donwload$c[reset]"
  fi

  _fast-download_run $URL $DIRECTORY
}

function _fast-download_run() {
  URL="$1"
  DIRECTORY=${2:=~/Downloads}

  echo "$c[dim]Downloading:$c[reset] $URL"
  echo "$c[dim]To:$c[reset] $DIRECTORY"
  if is not existing "$DIRECTORY"; then
    echo "$cs[error]Could not find$c[reset] $DIRECTORY"
    return 1
  fi
  aria2c -x 16 -s 16 $URL -d $DIRECTORY
}

fast-download "$@"
