#!/usr/bin/env zsh

function gcod() {
  local DEPS=(git)
  if ! deps $DEPS; then
    return 1
  fi

  local DEV_BRANCH=$(git config gitflow.branch.develop)
  if is empty "$DEV_BRANCH"; then
    echo "$c[error]error:$c[reset] no gitflow develop branch configured"
    echo "set it with: git config gitflow.branch.develop $c[em]develop$c[reset]"
    return 1
  fi

  git checkout "$DEV_BRANCH"
  if is not equal "$?" "0"; then
    echo "$c[error]error:$c[reset] could not checkout $DEV_BRANCH"
    return 1
  fi
}

gcod "$@"
