#!/usr/bin/env zsh

# gcom: Checks out master (git flow configured)
function gcom () {
  local DEPS=(
    is
    git
  )

  if ! deps $DEPS; then
    return
  fi

  MASTER_BRANCH=$(git config gitflow.branch.master)
  if is empty "$MASTER_BRANCH"; then
    MASTER_BRANCH=main
    # echo "$cs[error]Could not get master branch$c[reset]"
    # echo "$cs[sub]Make sure you are in a git repo and then run:$c[reset] git flow init"
    # return 1
  fi

  git checkout $MASTER_BRANCH
}

gcom "$@"
