#!/usr/bin/env zsh

# gcom: Checks out master (git flow configured)
function gcom () {
  local DEPS=(
    is
    git
    clr_red
    clr_white
  )

  if ! deps $DEPS; then
    return
  fi

  MASTER_BRANCH=$(git config gitflow.branch.master)
  if is empty "$MASTER_BRANCH"; then
    clr_red "Could not get master branch"
    clr_white "Make sure you are in a git repo and then run: git flow init"
    return 1
  fi

  git checkout $MASTER_BRANCH
}

gcom "$@"
