#!/usr/bin/env zsh

function gcom() {
  local DEPS=(git)
  if ! deps $DEPS; then
    return 1
  fi

  local MAIN_BRANCH=$(git config gitflow.branch.main)
  if is empty "$MAIN_BRANCH"; then
    MAIN_BRANCH=main
  fi

  git checkout "$MAIN_BRANCH"
  if is not equal "$?" "0"; then
    echo "$c[error]error:$c[reset] could not checkout $MAIN_BRANCH"
    echo "set it with: git config gitflow.branch.main $c[em]main$c[reset]"
    return 1
  fi
}

gcom "$@"
