#!/usr/bin/env zsh

_gpl_description="Prunes Local Branches"
_gpl_positional=""
_gpl_positional_desc=""
_gpl_flag_names[1]="--help"
_gpl_flag_messages[1]="shows help"
_gpl_flag_names[2]="--list"
_gpl_flag_messages[2]="lists branches to delete"
_gpl_flag_names[3]="--prune"
_gpl_flag_messages[3]="runs the prune"

function git-prune-local_prune() {
  echo "$cs[info]The following branches will be deleted$c[reset]"

  git-prune-local_list

  if confirm; then
    echo "$cs[success]Deleting stale branches$c[reset]"
    git branch -vv | grep 'origin/.*: gone]' | awk '{print $1}' | xargs git branch -D
  fi
}

function git-prune-local_list() {
  git branch -vv | grep 'origin/.*: gone]' | awk '{print $1}'
}

function git-prune-local() {
  local DEPS=(
    git
    grep
    awk
    xargs
    confirm
  )

  if ! deps $DEPS; then
    return
  fi

  if is empty "$1" || has-flag '--help' $@; then
    print-help \
      "$0" \
      "$_gpl_description" \
      "_gpl_flag_names" \
      "_gpl_flag_messages" \
      "$_gpl_positional" \
      "$_gpl_positional_desc"
    return 0
  fi

  if has-flag '--list' $@; then
    git-prune-local_list
    return $?
  fi

  if has-flag '--prune' $@; then
    git-prune-local_prune
    return $?
  fi
}

git-prune-local "$@"
