#!/usr/bin/env zsh

function git-i-really-fucked-up() {
  local DEPS=(
    confirm
    git
  )

  if ! deps $DEPS; then
    return
  fi

  local BRANCH="origin/$(git-branch)"
  echo "$c[success]Success:$c[reset] reset to $BRANCH"

  if confirm "$c[warning]Are you sure you want to reset to $BRANCH?$c[reset]"; then
    git reset --hard $BRANCH
  fi
}

git-i-really-fucked-up "$@"
