#!/usr/bin/env zsh

function git-i-really-fucked-up() {
  local DEPS=(
    confirm
    git
  )

  if ! deps $DEPS; then
    return
  fi

  local BRANCH="origin/$(git-branch)"
  echo "$cs[success]Reset to$c[reset] $BRANCH"

  if confirm; then
    git reset --hard $BRANCH
  fi
}

git-i-really-fucked-up "$@"
