#!/usr/bin/env zsh

function git-prune-local_prune() {
  echo "$c[info]The following branches will be deleted$c[reset]"

  git-prune-local_list

  if confirm; then
    echo "$c[success]Deleting stale branches$c[reset]"
    git branch -vv | grep 'origin/.*: gone]' | awk '{print $1}' | xargs git branch -D
  fi
}

function git-prune-local_list() {
  git branch -vv | grep 'origin/.*: gone]' | awk '{print $1}'
}

function git-prune-local() {
  local DEPS=(
    git
    grep
    awk
    xargs
    confirm
  )

  if ! deps $DEPS; then
    return
  fi

  if is empty "$1" || has-flag '--help' $@; then
    echo "$c[h1]git prune local$c[reset]"
    echo "$c[lead]Deletes local branches that have been deleted from the remote$c[reset]"
    echo ""
    echo "$c[h2]Usage:$c[reset]"
    echo "git-prune-local $c[flag][--help]$c[reset]"
    echo ""
    echo "$c[h2]Example:$c[reset]"
  fi

  echo "$c[info]The following branches will be deleted:$c[reset]"

  git-prune-local_list

  if confirm "$c[warning]Are you sure you want to delete these branches?$c[reset]"; then
    echo "$c[success]Deleting stale branches$c[reset]"
    git branch -vv | grep 'origin/.*: gone]' | awk '{print $1}' | xargs git branch -D
  fi
}

git-prune-local "$@"
