#!/usr/bin/env zsh

function history-purge() {
  local DEPS=(is)
  if ! deps $DEPS; then
    return 1
  fi

  if is equal "$1" "--help" || is empty "$1"; then
    echo "$c[h1]history-purge$c[reset]"
    echo ""
    echo "$c[lead]removes all history entries containing the given phrase. useful for removing accidentally typed secrets.$c[reset]"
    echo ""
    echo "$c[h2]usage$c[reset]"
    echo "  history-purge $c[param]<needle>$c[reset]"
    echo ""
    echo "$c[h2]examples$c[reset]"
    echo "  history-purge $c[param]'my-secret-token'$c[reset]"
    echo "  history-purge $c[param]'export AWS_SECRET'$c[reset]"
    return 0
  fi

  local NEEDLE="$1"

  echo "will remove all history entries containing $c[em]$NEEDLE$c[reset]"
  if confirm; then
    LC_ALL=C sed -i "/$NEEDLE/d" $HISTFILE
    echo "$c[success]success:$c[reset] history purged"
  else
    echo "$c[warn]warning:$c[reset] cancelled"
  fi
}

history-purge "$@"
