#!/usr/bin/env zsh

DEBUG_IS_M1=0

# Detects if architecture is arm64
function is-m1() {
  ARCH=$(uname -m)
  if is equal "$DEBUG_IS_M1" "1"; then
    echo "Arch is $ARCH"
  fi

  # It's M1 if osx and arch===arm64
  is-osx && is equal "$ARCH" "arm64"
}

is-m1 "$@"
