#!/usr/bin/env zsh

DEBUG_IS_OSX=0

# Detects if we're running on OSX
# Aim is to ensure we
# We can also use uname -m for architecture (arm64) and -p for base arch (arm)
function is-osx() {
  UNAME=$(uname)
  if is equal "$DEBUG_IS_OSX" "1"; then
    echo "UNAME is $UNAME"
  fi

  # It's OSX if UNAME===Darwin
  is equal "$UNAME" "Darwin"
}

is-osx "$@"
