#!/usr/bin/env zsh

DEBUG_IS_UBUNTU=0

# Detects if we're running on Ubuntu/deblike
# Aim is to ensure we
# We can also use uname -m for architecture (arm64) and -p for base arch (arm)
function is-ubuntu {
  UNAME=$(uname)
  if is equal "$DEBUG_IS_UBUNTU" "1"; then
    echo "UNAME is $UNAME"
    echo "$(command -v apt)"
  fi

  # It's Ubuntu/Deblike if Uname is Linux and apt is a callable command
  is equal "$UNAME" "Linux" && command -v apt > /dev/null
}

is-ubuntu "$@"
