#!/usr/bin/env zsh

function jdk() {
  # local DEPS=(

  # )

  # if ! deps $DEPS; then
  #   return
  # fi

  version=$1
  export JAVA_HOME=$(/usr/libexec/java_home -v"$version");
  java -version
}

jdk "$@"
