#!/usr/bin/env zsh

function _jet_usage() {
  clr_cyan 'Usage:' -n
  clr_white " $1 command\n"

  clr_cyan 'Commands:'
  clr_green 'help' -n
  clr_white ' - shows the help docs for frequently used folders/commands/etc.'
  clr_green 'edit-help' -n
  clr_white ' - Opens the help doc in sublime'
  # clr_green 'desktop-manager' -n
  # clr_white ' [manager] - Sets the display manager for next boot (default=unity)'
  # clr_green 'resolution' -n
  # clr_white ' [w] [h] - Sets the Virtual display resolution to [w]x[h]'
  # clr_green 'display-manager' -n
  # clr_white ' - Runs the command to set the display manager (default=gdm3)'
}

# jet: Jetson Nano helper function
function jet () {
  local DEPS=(
    is
    clr_cyan
    clr_green
    clr_white
    clr_red
  )

  if ! deps $DEPS; then
    return
  fi

  if is empty "$1"; then
    _jet_usage "$0"
    return 0
  fi


  if is equal "$1" "help"; then
    _jet_help
    return 0;
  fi

  if is equal "$1" "edit-help"; then
    _jet_edit_help
    return 0;
  fi

}

function _jet_help() {
  _jet_ensure_help

  if is not available "bat"; then
    clr_red "Bat not installed, using cat instead"
    cat $JET_HELP_FILE
  else
    bat $JET_HELP_FILE
  fi
}

function _jet_edit_help() {
  _jet_ensure_help

  subl $JET_HELP_FILE
}

function _jet_ensure_help() {
  if is not file "$JET_HELP_FILE"; then
    clr_red "Could not find help file at $JET_HELP_FILE"

    clr_cyan "Create it now?"

    if confirm; then
      echo "# Jetson Nano Notes" > $JET_HELP_FILE
      clr_green "Created help file"
    fi
  fi
}

jet "$@"
