#!/usr/bin/env zsh

#SOME_VAR="${SOME_VAR:-"default-value"}"

_ls_fns_description="Lists custom functions and their descriptions"
_ls_fns_positional=""
_ls_fns_positional_desc=""
_ls_fns_flag_names[1]="--help"
_ls_fns_flag_messages[1]="shows help"

function _ls_fns_list() {
  local fns=$(ls "$FN_DIR")

  echo "$cs[h2]Available Functions:$c[reset]"

  while IFS= read -r fn; do
    $fn --help &> /dev/null
    local fn_record="$cs[info]$fn$c[reset]"
    local underscored=${fn//-/_}
    local desc_ptr="_${underscored}_description"
    local description=${(P)${desc_ptr}}
    if is not empty "$description"; then
      fn_record="$fn_record - $description"
    fi

    echo $fn_record
  done <<< "$fns"
}

function ls-fns() {
  local DEPS=(
    is
  )

  if ! deps $DEPS; then
    return 1
  fi

  if has-flag '--help' $@; then
    print-help \
      "$0" \
      "$_ls_fns_description" \
      "_ls_fns_flag_names" \
      "_ls_fns_flag_messages" \
      "$_ls_fns_positional" \
      "$_ls_fns_positional_desc"
    return 0
  fi

  _ls_fns_list "$@"
}

ls-fns "$@"
