#!/usr/bin/env zsh

#SOME_VAR="${SOME_VAR:-"default-value"}"

_ls_fns_description="This is the description"
_ls_fns_positional="positional"
_ls_fns_positional_desc="This is a positional argument"
_ls_fns_flag_names[1]="--help"
_ls_fns_flag_messages[1]="shows help"
_ls_fns_flag_names[2]="--sub [param]"
_ls_fns_flag_messages[2]="Runs a sub function with [param]."

function _ls_fns_subfn() {
  if is empty "$1"; then
    echo "$cs[warn]Nothing passed to subfn$c[reset]"
    return 1
  fi

  echo "$cs[success]subfn$c[reset] $1"
}

function ls-fns() {
  local DEPS=(
    is
  )

  if ! deps $DEPS; then
    return 1
  fi

  if is empty "$1" || has-flag '--help' $@; then
    print-help \
      "$0" \
      "$_ls_fns_description" \
      "_ls_fns_flag_names" \
      "_ls_fns_flag_messages" \
      "$_ls_fns_positional" \
      "$_ls_fns_positional_desc"
    return 0
  fi

  local POSITIONAL="$@[-1]"

  if has-flag '--sub' $@; then
    _ls_fns_subfn "$(flag-value '--sub' $@)"
#    return $?
  fi

  if is not empty "$POSITIONAL"; then
    echo "$cs[param]$POSITIONAL$c[reset]"
  fi
}

ls-fns "$@"
