#!/usr/bin/env zsh

APP_PLACEHOLDER="[AppName]"

declare -A new_templates
new_templates[react-native]="npx react-native init $APP_PLACEHOLDER --template react-native-template-typescript"
new_templates[stencil]="npm init stencil"
new_templates[python]="poetry new $APP_PLACEHOLDER"

# Either creates a new project of a type or
new() {
  local DEPS=(
    is
    clr_red
    clr_white
    getopt
  )

  if ! deps $DEPS; then
    return
  fi


  if is not empty "$1"; then
    if is not empty "$new_templates[$1]"; then
      clr_cyan "To create a new " -n
      echo -n "$1 "
      clr_cyan "project:"
      echo ""
      clr_green "$new_templates[$1]"
      return
    else
      echo -n "$1 "
      clr_red " not found"
      echo ""
    fi
  fi

  _new_print_all
}

_new_print_all() {
  for key value in ${(kv)new_templates}; do
    echo -n "$key"; clr_cyan ": " -n; clr_green "$value"
  done
}

new "$@"
