#!/usr/bin/env zsh

# The function template
FN_TEMPLATE="${FN_TEMPLATE:-$CUSTOM_DIR/functions/template}"

_new_fn_description="Creates a new function in $CUSTOM_DIR/functions"
_new_fn_positional="name"
_new_fn_positional_desc="The function name"
_new_fn_flag_names[1]="--help"
_new_fn_flag_messages[1]="shows help"

function _new_fn_create() {
  if is empty "$1"; then
    echo "$cs[warn]Nothing passed to subfn$c[reset]"
    return 1
  fi

  echo "$cs[success]subfn$c[reset] $1"
}

function new-fn() {
  local DEPS=(
    is
  )

  if ! deps $DEPS; then
    return 1
  fi

  if is empty "$1" || has-flag '--help' $@; then
    print-help \
      "$0" \
      "$_new_fn_description" \
      "_new_fn_flag_names" \
      "_new_fn_flag_messages" \
      "$_new_fn_positional" \
      "$_new_fn_positional_desc"
    return 0
  fi

  local POSITIONAL="$@[-1]"

  if has-flag '--sub' $@; then
    _new_fn_subfn "$(flag-value '--sub' $@)"
#    return $?
  fi

  if is not empty "$POSITIONAL"; then
    echo "$cs[param]$POSITIONAL$c[reset]"
  fi
}

new-fn "$@"
