#!/usr/bin/env zsh

_ns_release_description="Performs an release with nativescript"
_ns_release_positional=""
_ns_release_positional_desc=""
_ns_release_flag_names[1]="--help"
_ns_release_flag_messages[1]="shows help"
_ns_release_flag_names[2]="--build-id [build-id]"
_ns_release_flag_messages[2]="Bumps --build-id to [build-id]"
_ns_release_flag_names[3]="--ios"
_ns_release_flag_messages[3]="Performs an iOS release"

_ns-release_set-build-id() {
  local INFO_PLIST="./App_Resources/iOS/Info.plist"
  local BUILD_ID=$2
  /usr/libexec/PlistBuddy $INFO_PLIST -c "set CFBundleVersion $BUILD_ID"
}

_ns-release_build-id() {
  local INFO_PLIST="./App_Resources/iOS/Info.plist"
  /usr/libexec/PlistBuddy $INFO_PLIST -c "print CFBundleVersion"
}
_ns-release_short-version() {
  local INFO_PLIST="./App_Resources/iOS/Info.plist"
  /usr/libexec/PlistBuddy $INFO_PLIST -c "print CFBundleShortVersionString"
}

_ns-release_build() {
  local INFO_PLIST="./App_Resources/iOS/Info.plist"
  SHORT_VERSION=$(_ns-release_short-version $INFO_PLIST)
  BUILD_ID=$(_ns-release_build-id $INFO_PLIST)
  DESKTOP_DIR="$HOME/Desktop"

  FINAL_PATH="$DESKTOP_DIR/engineius-$SHORT_VERSION-$BUILD_ID.ipa"
  echo "$cs[info]Building$c[reset] $SHORT_VERSION-$BUILD_ID"
  echo "$cs[info]to$c[reset] $FINAL_PATH"

  if ! confirm; then
    echo "$cs[yellow]Okay Then, ignore me$c[reset]"
    return
  fi

  clr_green "$cs[info]Running Build Command:$c[reset]"

  ns build ios \
    --for-device \
    --release \
    --env.uglify \
    --env.aot \
    --env.production \
    --copy-to "$FINAL_PATH" \
    --provision "Engineius Distribution Profile 2022"

  # ns build android --release --env.uglify --env.aot --env.production --key-store-path ../secrets/vme-release-key.jks --key-store-password androidP4ssword --key-store-alias vme-alias --key-store-alias-password androidP4ssword --copy-to /Users/jamesmacmillan/Desktop/engineius-1.5.7-157220434.apk
}


ns-release() {
  # /Users/jamesmacmillan/projects/engineius/mobile-app/App_Resources/iOS/Info
  local INFO_PLIST="./App_Resources/iOS/Info.plist"
  local DEPS=(
    is
    clr_cyan
    clr_green
    clr_white
    clr_red
    git
    current_branch
    plistbuddy
  )

  if ! deps $DEPS; then
    return
  fi

  if is empty "$1" || has-flag '--help' $@; then
    print-help \
      "$0" \
      "$_ns_release_description" \
      "_ns_release_flag_names" \
      "_ns_release_flag_messages" \
      "$_ns_release_positional" \
      "$_ns_release_positional_desc"
    return 0
  fi

  if is not existing $INFO_PLIST; then
    echo "$cs[warn]Cannot find$c[reset] $INFO_PLIST$cs[warn], are you in the right directory?$c[reset]"
    return
  fi

  if has-flag '--build-id' $@; then
    local BUILD_ID=$(flag-value '--build-id' $@)
    echo "$cs[info]Updating BUILD_ID to:$c[reset] $1"
    _ns-release_set-build-id "$1"
  fi

  if has-flag '--ios' $@; then
    _ns-release_build
  fi
}

ns-release "$@"
