#!/usr/bin/env zsh

# Prints a consistent help message
# Provided an array of flags and the command name
# Example Usage:
#
# Declarations:
#
#_update_description="This is the command description"
#_update_positional="positional-param"
#_update_positional_desc="This is the positional parameter description"
#_update_flag_names[1]="--help"
#_update_flag_messages[1]="shows help"
#
# Invocation:
#
#if is empty "$1" || has-flag '--help' $@; then
#  print-help \
#    "$0" \
#    "$_update_description" \
#    "_update_flag_names" \
#    "_update_flag_messages" \
#    "$_update_positional" \
#    "$_update_positional_desc"
#  return 0
#fi
function print-help() {
  COMMAND="$1"
  DESCRIPTION="$2"
  FLAG_NAMES="$3"
  FLAG_DESCRIPTIONS="$4"
  MANDATORY_PARAMETER="$5"
  MANDATORY_PARAMETER_DESCRIPTION="$6"

  local DEPS=(
    is
  )

  if ! deps $DEPS; then
    return
  fi

  if is empty "$COMMAND"; then
    return
  fi

  echo "\n$cs[h1]$COMMAND$c[reset]"

  echo "\n$cs[h2]Description:$c[reset] $DESCRIPTION\n"

  echo "$cs[h2]Usage:$c[reset] $1 $cs[flag][flags]$c[reset] $cs[param]$MANDATORY_PARAMETER$c[reset]\n"
  if is not empty "$MANDATORY_PARAMETER"; then
    print-parameter $MANDATORY_PARAMETER $MANDATORY_PARAMETER_DESCRIPTION
  fi

  print-flags "$3" "$4"
}

print-help "$@"
