#!/usr/bin/env zsh

function print-flags() {
  local DEPS=(
    is
  )

  if ! deps $DEPS; then
    return
  fi

  if is empty "$1"; then
    return
  fi
  typeset -a names=(${(P)${1}})
  typeset -a messages=(${(P)${2}})

  echo "$c[dim]Flags:$c[reset]"

  local index=1
  for n in $names
  do
    echo "$c[cyan]$names[$index]$c[reset]: $messages[$index]"
    index=$(expr $index + 1)
  done
}

print-flags "$@"
