#!/usr/bin/env zsh

# Prints a consistent help message
# Provided an array of flags and the command name
# Example Usage:
#
# _update_description="This is the command description"
# _update_flag_names[1]="--help"
# _update_flag_messages[1]="shows help"
#
# print-help "$0" "$_update_description" "_update_flag_names" "_update_flag_messages" "Mandatory Parameter" "Mandatory Parameter Description"
function print-help() {
  COMMAND="$1"
  DESCRIPTION="$2"
  FLAG_NAMES="$3"
  FLAG_DESCRIPTIONS="$4"
  MANDATORY_PARAMETER="$5"
  MANDATORY_PARAMETER_DESCRIPTION="$6"

  local DEPS=(
    is
  )

  if ! deps $DEPS; then
    return
  fi

  if is empty "$COMMAND"; then
    return
  fi

  echo "\n$COMMAND"

  echo "\n$c[dim]Description:$c[reset] $DESCRIPTION\n"

  echo "$c[dim]Usage:$c[reset] $1 $c[cyan][flags]$c[reset] $c[magenta]$MANDATORY_PARAMETER$c[reset]\n"
  if is not empty "$MANDATORY_PARAMETER"; then
    print-parameter $MANDATORY_PARAMETER $MANDATORY_PARAMETER_DESCRIPTION
  fi

  print-flags "$3" "$4"
}

print-help "$@"
