#!/usr/bin/env zsh

function print-flags() {
  local DEPS=(
    is
  )

  if ! deps $DEPS; then
    return
  fi

  if is empty "$1"; then
    return
  fi
  typeset -a names=(${(P)${1}})
  typeset -a messages=(${(P)${2}})

  echo "$c[dim]Flags:$c[reset]"

  local index=1
  for n in $names
  do
    name="$names[$index]"
    if is substring "[" "$name"; then
      before_rep="$c[magenta]["
      name=${name//\[/$before_rep}
    fi
    name="$c[cyan]$name$c[reset]"

    message="$messages[$index]"
    if is substring "[" "$message"; then
      before_rep="$c[magenta]["
      after_rep="]$c[reset]"
      message=${message//\[/$before_rep}
      message=${message//\]/$after_rep}
    fi

    echo "$name: $message"
    index=$(expr $index + 1)
  done
}

print-flags "$@"
