#!/usr/bin/env zsh

function print-flags() {
  local DEPS=(
    is
    clr_red
    clr_green
    clr_white
    clr_cyan
  )

  if ! deps $DEPS; then
    return
  fi

  if is empty "$1"; then
    return
  fi
  typeset -a names=(${(P)${1}})
  typeset -a messages=(${(P)${2}})

  clr_cyan 'Flags:'

  local index=1
  for n in $names
  do
    clr_green "\0-$names[$index]: " -n;
    clr_white "$messages[$index]"

    index=$(expr $index + 1)
  done
}

print-flags "$@"
