#!/usr/bin/env zsh

# Per Directory History P10k
function prompt_my_per_dir_status() {
    if $_per_directory_history_is_global; then
        p10k segment -i ' Global'
    else
        p10k segment -i ' Local'
    fi
}

prompt_my_per_dir_status "$@"
