#!/usr/bin/env zsh

_pyloader_description="Manages pyload install as a docker container"
_pyloader_flag_names[1]="--help"
_pyloader_flag_messages[1]="shows help"
_pyloader_flag_names[2]="--install"
_pyloader_flag_messages[2]="installs pyload using the docker container"
_pyloader_flag_names[3]="--start"
_pyloader_flag_messages[3]="starts pyload"
_pyloader_flag_names[4]="--open"
_pyloader_flag_messages[4]="opens pyload in the browser"
_pyloader_flag_names[5]="--stop"
_pyloader_flag_messages[5]="stops pyload"
_pyloader_flag_names[6]="--logs"
_pyloader_flag_messages[6]="shows the pyload logs"
_pyloader_flag_names[7]="--config"
_pyloader_flag_messages[7]="shows the pyload config"

function _pyloader_config() {
  PYLOAD_NAME="${PYLOAD_NAME:-pyload}"
  CONFIG_DIR="${PYLOAD_CONFIG:-$HOME/.pyload}"
  DOWNLOAD_DIR="${PYLOAD_DOWNLOAD:-$HOME/downloads}"
  echo "$cs[info]PYLOAD_NAME:$c[reset] $PYLOAD_NAME"
  echo "$cs[info]CONFIG_DIR:$c[reset] $CONFIG_DIR"
  echo "$cs[info]DOWNLOAD_DIR:$c[reset] $DOWNLOAD_DIR"
}

function _pyloader_install() {
  PYLOAD_NAME="${PYLOAD_NAME:-pyload}"
  CONFIG_DIR="${PYLOAD_CONFIG:-$HOME/.pyload}"
  DOWNLOAD_DIR="${PYLOAD_DOWNLOAD:-$HOME/downloads}"

  echo "$cs[info]Creating pyload container with following config:$c[reset]"
  echo "$cs[info]PYLOAD_NAME:$c[reset] $PYLOAD_NAME"
  echo "$cs[info]CONFIG_DIR:$c[reset] $CONFIG_DIR"
  echo "$cs[info]DOWNLOAD_DIR:$c[reset] $DOWNLOAD_DIR"
  docker run -d \
    --name=$PYLOAD_NAME \
    -e PUID=501 \
    -e PGID=20 \
    -e TZ=Europe/London \
    -p 8000:8000 \
    -p 9666:9666 `#optional` \
    -v $CONFIG_DIR:/config \
    -v $DOWNLOAD_DIR:/downloads \
    --restart unless-stopped \
    lscr.io/linuxserver/pyload-ng
}

function _pyloader_start() {
  PYLOAD_NAME="${PYLOAD_NAME:-pyload}"
  echo "$cs[info]Starting$c[reset] $PYLOAD_NAME"
  docker start pyload
}

function _pyloader_stop() {
  PYLOAD_NAME="${PYLOAD_NAME:-pyload}"
  echo "$cs[info]Stopping$c[reset] $PYLOAD_NAME"
  docker stop pyload
}

function _pyloader_logs() {
  PYLOAD_NAME="${PYLOAD_NAME:-pyload}"
  echo "$cs[info]Logs for$c[reset] $PYLOAD_NAME"
  docker logs -f pyload
}

function _pyloader_open() {
  open "http://localhost:8000"
}

# pyloader: Lazy issue mentions in a git commit -m
function pyloader () {
  local DEPS=(
    is
    docker
  )

  if ! deps $DEPS; then
    return
  fi

  if is empty "$1" || has-flag '--help' $@; then
    print-help \
      "$0" \
      "$_pyloader_description" \
      "_pyloader_flag_names" \
      "_pyloader_flag_messages" \
      "$_pyloader_positional" \
      "$_pyloader_positional_desc"
    return 0
  fi

  if has-flag '--install' $@; then
    _pyloader_install
    return 0;
  fi

  if has-flag '--start' $@; then
    _pyloader_start
    return 0;
  fi

  if has-flag '--stop' $@; then
    _pyloader_stop
    return 0;
  fi

  if has-flag '--logs' $@; then
    _pyloader_logs
    return 0;
  fi

  if has-flag '--config' $@; then
    _pyloader_config
    return 0;
  fi

  if has-flag '--open' $@; then
    _pyloader_open
    return 0;
  fi
}

pyloader "$@"
