#!/usr/bin/env zsh

FN_DIR=${FN_DIR:=$CUSTOM_DIR/functions}

function _reload_do() {
  local FN="$1"
  unfunction "$FN" 2>/dev/null
  autoload -Uz "$FN"
  echo "$c[success]reloaded:$c[reset] $FN"
}

function reload() {
  local DEPS=(is)
  if ! deps $DEPS; then
    return 1
  fi

  if is equal "$1" "--help" || is empty "$1"; then
    echo "$c[h1]reload$c[reset]"
    echo ""
    echo "$c[lead]reloads a zsh function by name, or all functions at once.$c[reset]"
    echo ""
    echo "$c[h2]usage$c[reset]"
    echo "  reload $c[param]<function>$c[reset]"
    echo "  reload $c[param]all$c[reset]"
    echo ""
    echo "$c[h2]examples$c[reset]"
    echo "  reload $c[param]update$c[reset]"
    echo "  reload $c[param]all$c[reset]"
    return 0
  fi

  local FN="$1"

  if is equal "$FN" "all"; then
    local FNS=$(ls $FN_DIR)
    while IFS= read -r FN; do
      _reload_do "$FN"
    done <<< "$FNS"
    return $?
  fi

  _reload_do "$FN"
}

reload "$@"
