#!/usr/bin/env zsh

_rider_description="Opens rider"
_rider_positional="path to sln"
_rider_positional_desc="The path to the .sln/.csproj file to open, or '.' to use the file in the current directory."
_rider_flag_names[1]="--help"
_rider_flag_messages[1]="shows help"

function _rider_find_sln() {
  SLN=$(ls -1 | grep .sln | head -1)
  PROJ=$(ls -1 | grep .csproj | head -1)

  if is empty "$SLN"; then
    if is empty "$PROJ"; then
      echo ".sln/.csproj $cs[error]not found in current directory.$c[red]"
      return 1
    fi

    open -na "/Applications/Rider.app" --args "$PROJ"
    return 0
  fi

  open -na "/Applications/Rider.app" --args "$SLN"
  return 0
}

# Webstorm Open Here
function rider () {
  local DEPS=(
    is
  )

  if is not existing "/Applications/Rider.app"; then
    echo "$cs[error]Rider not installed$c[reset]";
    return 1
  fi

  if is empty "$1" || has-flag '--help' $@; then
    print-help \
      "$0" \
      "$_rider_description" \
      "_rider_flag_names" \
      "_rider_flag_messages" \
      "$_rider_positional" \
      "$_rider_positional_desc"
    return 0
  fi

  if is equal "$1" "."; then
    _rider_find_sln
    return $?
  fi

  open -na "/Applications/Rider.app" --args "$@"
}

rider "$@"
