#!/usr/bin/env zsh

function _rider_find_sln() {
  SLN=$(ls -1 | grep .sln | head -1)
  PROJ=$(ls -1 | grep .csproj | head -1)

  if is empty "$SLN"; then
    if is empty "$PROJ"; then
      echo ".sln/.csproj $cs[error]not found in current directory.$c[red]"
      return 1
    fi

    open -na "/Applications/Rider.app" --args "$PROJ"
    return 0
  fi

  open -na "/Applications/Rider.app" --args "$SLN"
  return 0
}

# Webstorm Open Here
function rider () {
  local DEPS=(
    is
  )

  if is not existing "/Applications/Rider.app"; then
    echo "$cs[error]Rider not installed$c[reset]";
    return 1
  fi

  if is equal "$1" "."; then
    _rider_find_sln
    return $?
  fi

  open -na "/Applications/Rider.app" --args "$@"
}

rider "$@"
