#!/usr/bin/env zsh

# Try get to mobile app's docs folder
function sim-docs () {
  local DEPS=(
    is
    clr_cyan
    clr_green
    clr_white
    clr_red
  )

  if ! deps $DEPS; then
    return
  fi

  if is not existing "logs/ios.sim.log"; then
    clr_red "could not find logs/ios.sim.log file"
    return 1;
  fi

  LOCATE_FILE=$(cat logs/ios.sim.log | rg "\s/.*?Documents/locate.txt" -o | head -n 1 | sed -e 's/^[[:space:]]*//')
  JUST_FOLDER="${LOCATE_FILE%/*}"

  if is not existing "$JUST_FOLDER"; then
    echo "Found but cannot cd to $JUST_FOLDER";
    return 1;
  fi

  open $JUST_FOLDER
}

sim-docs "$@"
