#!/usr/bin/env zsh

CNF_FILE="$HOME/.sql-db.cnf"
DB_HOST="james-ubuntu"
DB_PORT="3306"
DB_USER="root"
DB_PASS="engineius"
DB_NAME="app_prod_2021-01-14"

# Restores a sql database to a new db
function sql() {
  local DEPS=(
    is
    clr_cyan
    clr_white
    mysql
  )

  if ! deps $DEPS; then
    return
  fi

  _sql-db_create-conf
  _sql-run
  _sql_remove-conf
}

function _sql-run() {
  if is not empty "$DB_NAME"; then
    mysql --defaults-extra-file=$CNF_FILE "$DB_NAME"
  else
    mysql --defaults-extra-file=$CNF_FILE
  fi
}

function _sql-db_create-conf() {
  echo "[client]" > $CNF_FILE
  echo "user=$DB_USER" >> $CNF_FILE
  echo "password=$DB_PASS" >> $CNF_FILE
  echo "host=$DB_HOST" >> $CNF_FILE
  echo "port=$DB_PORT" >> $CNF_FILE
}

function _sql_remove-conf() {
  if is existing "$CNF_FILE"; then
    if is equal "1" "$DEBUG"; then
      clr_cyan "Deleting $CNF_FILE"
    fi
    rm $CNF_FILE
  fi
}

sql "$@"
