#!/usr/bin/env zsh

ORG="${ORG:-7digital}"
PROJECT_DIR="${PROJECT_DIR:-$HOME/projects/$ORG}"
USER_NAME="${USER_NAME:-jamesm}"
GH_REPO="${GH_REPO:-developer-cloud-workstation}"
WORKFLOW_ID="${WORKFLOW_ID:-Start Workstation}"

function _start_workstation_local_dir() {
  if is not existing "$PROJECT_DIR"; then
    echo "$c[info]creating:$c[reset] $PROJECT_DIR"
    mkdir -p "$PROJECT_DIR"
  fi
}

function _start_workstation_gh_logged_in() {
  local STATUS=$(gh auth status 2>&1)
  if is not equal "$?" "0"; then
    echo "$c[warn]warning:$c[reset] github cli needs auth."
    echo "run $c[em]gh auth login$c[reset] then try again"
    echo "$STATUS"
    return 1
  fi
}

function _start_workstation_repo() {
  if is not existing "$PROJECT_DIR/$GH_REPO"; then
    local OUTPUT=$(cd "$PROJECT_DIR" && gh repo clone "$ORG/$GH_REPO" 2>&1)
    if is not equal "$?" "0"; then
      echo "$c[error]error:$c[reset] could not clone $GH_REPO"
      echo "$OUTPUT"
      return 1
    fi
  fi
}

function _start_workstation_run_action() {
  local OUTPUT=$(cd "$PROJECT_DIR/$GH_REPO" && gh workflow run "$WORKFLOW_ID" -f name=$USER_NAME 2>&1)
  if is not equal "$?" "0"; then
    echo "$c[error]error:$c[reset] could not run workflow"
    echo "$OUTPUT"
    return 1
  fi
}

function start-workstation() {
  local DEPS=(is gh)
  if ! deps $DEPS; then
    return 1
  fi

  _start_workstation_gh_logged_in || return 1
  _start_workstation_local_dir
  _start_workstation_repo || return 1
  _start_workstation_run_action || return 1

  echo "$c[success]success:$c[reset] workstation started"
}

start-workstation "$@"
