#!/usr/bin/env zsh

TOUCH_SUDO_FILE=${TOUCH_SUDO_FILE:=/etc/pam.d/sudo}

_touch_sudo_description="Enables TouchID Sudo-ing"
_touch_sudo_positional=""
_touch_sudo_positional_desc=""
_touch_sudo_flag_names[1]="--help"
_touch_sudo_flag_messages[1]="shows help"

function _touch-sudo-update-sudo() {
  sudo chown $(whoami) $TOUCH_SUDO_FILE
  sudo chmod +w $TOUCH_SUDO_FILE
  cat > $TOUCH_SUDO_FILE << EOF
# sudo: auth account password session
auth       sufficient     pam_tid.so
auth       sufficient     pam_smartcard.so
auth       required       pam_opendirectory.so
account    required       pam_permit.so
password   required       pam_deny.so
session    required       pam_permit.so
EOF
  sudo chmod -w $TOUCH_SUDO_FILE
  sudo chown root $TOUCH_SUDO_FILE
  echo "$cs[success]Done$c[reset]"
  echo "$cs[info]run$c[reset] cat $TOUCH_SUDO_FILE $cs[info]to check$c[reset]"
}

# touch-sudo: Lazy issue mentions in a git commit -m
function touch-sudo () {
  local DEPS=(
    is
    clr_cyan
    clr_green
    clr_white
    clr_red
    confirm
  )

  if ! deps $DEPS; then
    return
  fi

  if has-flag '--help' $@; then
    print-help \
      "$0" \
      "$_touch_sudo_description" \
      "_touch_sudo_flag_names" \
      "_touch_sudo_flag_messages" \
      "$_touch_sudo_positional" \
      "$_touch_sudo_positional_desc"
    return 0
  fi

  if is not osx; then
    echo "$cs[error]Can't do that on non-osx$c[reset]"
    return 1
  fi

  if confirm "$cs[warn]Enable touch Sudo?$c[reset]"; then
    echo "$cs[info]Enabling$c[reset]"
    _touch-sudo-update-sudo
  else
    echo "$cs[info]Not Enabling$c[reset]"
  fi
}

touch-sudo "$@"
