#!/usr/bin/env zsh

TOUCH_SUDO_FILE=${TOUCH_SUDO_FILE:=/etc/pam.d/sudo}

function _touch-sudo-update-sudo() {
  sudo chown $(whoami) $TOUCH_SUDO_FILE
  sudo chmod +w $TOUCH_SUDO_FILE
  cat > $TOUCH_SUDO_FILE << EOF
# sudo: auth account password session
auth       sufficient     pam_tid.so
auth       sufficient     pam_smartcard.so
auth       required       pam_opendirectory.so
account    required       pam_permit.so
password   required       pam_deny.so
session    required       pam_permit.so
EOF
  sudo chmod -w $TOUCH_SUDO_FILE
  sudo chown root $TOUCH_SUDO_FILE
  echo "$c[success]success:$c[reset] touch sudo enabled"
  echo "run $c[em]cat $TOUCH_SUDO_FILE$c[reset] to verify"
}

function touch-sudo() {
  local DEPS=(is confirm)
  if ! deps $DEPS; then
    return 1
  fi

  if is equal "$1" "--help"; then
    echo "$c[h1]touch-sudo$c[reset]"
    echo ""
    echo "$c[lead]enables touchid authentication for sudo (macos only).$c[reset]"
    echo ""
    echo "$c[h2]usage$c[reset]"
    echo "  touch-sudo $c[flag][--help]$c[reset]"
    return 0
  fi

  if is not osx; then
    echo "$c[error]error:$c[reset] touch-sudo is macos only"
    return 1
  fi

  if confirm "$c[warn]enable touch sudo?$c[reset]"; then
    echo "$c[info]enabling:$c[reset] touch sudo"
    _touch-sudo-update-sudo
  else
    echo "$c[warn]warning:$c[reset] cancelled"
  fi
}

touch-sudo "$@"
