#!/usr/bin/env zsh

# alias wso='open -na "WebStorm.app" --args "$(pwd)"'

# ls -1 | grep 'WebStorm'

function _ws_stable() {
  stable_app=$(cd /Applications && ls -1 | rg -i 'webstorm.app' --color never)
  if is not equal "" "$stable_app"; then
    open -na "$stable_app" --args "$@"
    return 0;
  fi

  clr_red 'Could not find webstorm, check it is installed'
  return 1;
}

function _ws_eap() {
  eap_app=$(cd /Applications && ls -1 | rg -i 'webstorm.*eap.*$' --color never)

  if is not equal "" "$eap_app"; then
    open -na "$eap_app" --args "$@"
    return 0;
  fi

  # clr_red 'Could not find webstorm eap, falling back to stable'
  _ws_stable "$@"
}

# Webstorm Open Here
function ws () {
  local DEPS=(
    is
    clr_cyan
    clr_green
    clr_white
    clr_red
  )

  if is equal "$1" "--stable"; then
    _ws_stable "${@:2}"
    return 0;
  fi

  _ws_eap "$@"
}

ws "$@"
