#!/usr/bin/env zsh

WS_LOCATION="/Applications/WebStorm.app"

_ws_description="Opens Webstorm given the path provided"
_ws_flag_names[1]="--help"
_ws_flag_messages[1]="shows help"

function _ws_stable() {
  if is existing /Applications/WebStorm.app; then
    open -na "$WS_LOCATION" --args "$@"
    return 0;
  fi

  echo "$c[red]Could not find webstorm at$c[reset] $WS_LOCATION$c[red], check it is installed.$c[reset]"
  return 1;
}

# Webstorm Open Here
function ws () {
  local DEPS=(
    is
  )

  if ! deps $DEPS; then
    return 1
  fi

  if has-flag '--help' $@; then
    print-help "$0" "$_ws_description" "_ws_flag_names" "_ws_flag_messages" "path" "The path to open"
    return
  fi

  _ws_stable "$@"
}

ws "$@"
