#!/usr/bin/env zsh

async_methods=(
  "0a"
  "0b"
  "0c"
)

export LOAD_METHOD='light'

function zload() {
 local DEPS=(
    clr_cyan
    is
    zinit
  )

  if ! deps $DEPS; then
    return
  fi

  if is equal "snippet" "$1"; then
    _log "Loading snippet $2"
    zinit snippet $2
    return
  fi

  if _is_async "$1"; then
    _async_load "$@"
  else
    _sync_load "$1"
  fi

}

function _is_async() {
  local needle=$1
  if (($async_methods[(Ie)$needle])); then
    return 0;
  fi

  return 1;
}

function _async_load() {
  if is equal "2" "$#"; then
    _log "loading $2 async"
    zinit ice wait"$1" lucid
    zinit $LOAD_METHOD $2
  else
    the_wait=$1
    ice_commands=${@:2:-1}
    plugin="${@:(-1)}"

    _log "loading $plugin async $the_wait, with ice $ice_commands"
    zinit ice wait"$the_wait" $ice_commands lucid
    zinit $LOAD_METHOD $plugin
  fi
}

function _sync_load() {
  _log "loading $1 sync"
  zinit $LOAD_METHOD $1
}

function _log() {
  if is equal "1" "$ZINIT_DEBUG"; then
    clr_cyan $*
  fi
}

zload "$@"
