#!/usr/bin/env zsh

source $CUSTOM_DIR/functions/is

SOURCE_DIR=${0:a:h}

INSTALL_SCRIPT_SOURCE="https://getmic.ro"
CONFIG_DEST="$HOME/.config/micro"
CONFIG_SOURCE="$SOURCE_DIR/micro-config"

local micro_plugins=(
  cheat
  filemanager
  jump
  manipulator
  palettero
)

if is not available "curl"; then
  echo "curl is required to install micro, please install it and try again"
  exit 1
fi

if is not available "micro"; then
  echo "Installing micro from $INSTALL_SCRIPT_SOURCE"
  curl -fsSL "$INSTALL_SCRIPT_SOURCE" | sh
  sudo mv ./micro /usr/local/bin/
  sudo chmod +x /usr/local/bin/micro
  echo "Installed micro to /usr/local/bin/micro"
else
  echo "micro is already installed, skipping installation"
fi

# install plugins
for plugin in "${micro_plugins[@]}"; do
  if micro -plugin list | grep -q "$plugin"; then
    echo "micro plugin $plugin already installed, skipping"
  else
    echo "Installing micro plugin $plugin"
    micro -plugin install "$plugin"
  fi
done

if is not dir "$CONFIG_DEST"; then
  echo "Creating micro config directory at $CONFIG_DEST"
  mkdir -p "$CONFIG_DEST"
else
  echo "micro config directory already exists at $CONFIG_DEST, skipping creation"
fi

# if bindings.json is a file and not a symlink
if [[ -f "$CONFIG_DEST/bindings.json" && ! -L "$CONFIG_DEST/bindings.json" ]]; then
  rm "$CONFIG_DEST/bindings.json"
  echo "Removed existing micro bindings.json file at $CONFIG_DEST/bindings.json to prepare for new configuration"
else
  echo "No existing micro bindings.json file found at $CONFIG_DEST/bindings.json, skipping removal"
fi

# same for settings.json
if [[ -f "$CONFIG_DEST/settings.json" && ! -L "$CONFIG_DEST/settings.json" ]]; then
  rm "$CONFIG_DEST/settings.json"
  echo "Removed existing micro settings.json file at $CONFIG_DEST/settings.json to prepare for new configuration"
else
  echo "No existing micro settings.json file found at $CONFIG_DEST/settings.json, skipping removal"
fi

# link ./micro/bindings.json to $CONFIG_DEST/bindings.json
if [[ -L "$CONFIG_DEST/bindings.json" ]]; then
  echo "micro bindings.json already linked at $CONFIG_DEST/bindings.json, skipping linking"
else
  ln -s "$CONFIG_SOURCE/bindings.json" "$CONFIG_DEST/bindings.json"
  echo "Linked micro bindings.json from $CONFIG_SOURCE/bindings.json to $CONFIG_DEST/bindings.json"
fi

# link ./micro/settings.json to $CONFIG_DEST/settings.json
if [[ -L "$CONFIG_DEST/settings.json" ]]; then
  echo "micro settings.json already linked at $CONFIG_DEST/settings.json, skipping linking"
else
  ln -s "$CONFIG_SOURCE/settings.json" "$CONFIG_DEST/settings.json"
  echo "Linked micro settings.json from $CONFIG_SOURCE/settings.json to $CONFIG_DEST/settings.json"
fi