#!/usr/bin/env zsh

# The directory this install script runs from
SOURCE_DIR=${0:a:h}

if [[ -z "$HOME" ]]; then
  echo '$HOME not set, set it before running this script'
  exit 1
fi

source ./functions/is

# Expected destination
DEST_DIR=$HOME/.custom
DEST_ZSHRC=$HOME/.zshrc
DEST_ZSHENV=$HOME/.zshenv

echo 'Linking zsh-config:'
echo "From: $SOURCE_DIR"
echo "To: $DEST_DIR"
echo "linking .zshrc to: $DEST_ZSHRC"
echo "linking .zshenv to: $DEST_ZSHENV"

# Clean old instances if they exist
if [[ -h $DEST_DIR ]]; then
  rm $DEST_DIR
fi

if [[ -h $DEST_ZSHRC ]]; then
  rm $DEST_ZSHRC
fi

if [[ -h $DEST_ZSHENV ]]; then
  rm $DEST_ZSHENV
fi

if [[ -h $HOME/.default-python-packages ]]; then
  rm $HOME/.default-python-packages
fi

sudo ln -s $SOURCE_DIR $DEST_DIR
sudo ln -s $DEST_DIR/.zshrc $DEST_ZSHRC
sudo ln -s $DEST_DIR/.zshenv $DEST_ZSHENV
sudo ln -s $DEST_DIR/.default-python-packages $HOME/.default-python-packages