#!/usr/bin/env zsh

# link Sublime Snippets
local SHARED_FILES=$HOME/.custom/sublime
echo 'Linking Sublime Snippets'

local SUBLIME_SETTINGS=""

if  [[ "$(uname)" == "Darwin" ]]; then
  # Is OSX
  SUBLIME_SETTINGS=~/Library/Application\ Support/Sublime\ Text\ 3/Packages/User
elif [[ -f "/etc/arch-release" ]]; then
  # Is Arch
  SUBLIME_SETTINGS=~/.config/sublime-text/Packages/User
else
  echo 'Not sure where to put snippets.'
  echo "Do sudo ln -s $SHARED_FILES/snippets [Sublime Packages User directory]"
fi

if [[ "$SUBLIME_SETTINGS" != "" ]]; then
  echo "From $SHARED_FILES"
  echo "To $SUBLIME_SETTINGS"

  if [[ -h $SUBLIME_SETTINGS/snippets || -e $SUBLIME_SETTINGS/snippets ]]; then
    echo 'Snippets already exists, replacing it'
    rm $SUBLIME_SETTINGS/snippets
  fi

  ln -s $SHARED_FILES/snippets $SUBLIME_SETTINGS/snippets

  if [[ -h $SUBLIME_SETTINGS/Preferences.sublime-settings || -e $SUBLIME_SETTINGS/Preferences.sublime-settings ]]; then
    echo 'Preferences.sublime-settings already exists, replacing it'
    rm $SUBLIME_SETTINGS/Preferences.sublime-settings
  fi

  ln -s $SHARED_FILES/Preferences.sublime-settings $SUBLIME_SETTINGS/Preferences.sublime-settings

  if [[ -h $SUBLIME_SETTINGS/Default.sublime-keymap || -e $SUBLIME_SETTINGS/Default.sublime-keymap ]]; then
    echo 'Default.sublime-keymap already exists, replacing it'
    rm $SUBLIME_SETTINGS/Default.sublime-keymap
  fi

  ln -s $SHARED_FILES/Default.sublime-keymap $SUBLIME_SETTINGS/Default.sublime-keymap

  if [[ -h $SUBLIME_SETTINGS/Default.sublime-mousemap || -e $SUBLIME_SETTINGS/Default.sublime-mousemap ]]; then
    echo 'Default.sublime-mousemap already exists, replacing it'
    rm $SUBLIME_SETTINGS/Default.sublime-mousemap
  fi

  ln -s $SHARED_FILES/Default.sublime-mousemap $SUBLIME_SETTINGS/Default.sublime-mousemap

  echo 'Done'
else
  echo 'Nothing to do here.'
fi
