#!/usr/bin/env zsh

source "${0:a:h}/installers/_stub"

if is equal "$1" "--help"; then
  echo "$c[h1]Install Everything$c[reset]"
  echo "$c[lead]requires zsh, and \$HOME to be set$c[reset]"
  echo ""
  echo "$c[info-small]Shell:$c[reset] $SHELL"
  echo "$c[info-small]HOME:$c[reset] $HOME"
  echo ""
  echo "$c[h2]Usage:$c[reset]"
  echo "install $c[flag][--help]$c[reset]"
  exit 0
fi

LEGACY_DIR="$REPO_DIR/legacy-uninstallers"
LEGACY_SCRIPTS=$(ls -1 $LEGACY_DIR | grep -v '.DS_Store' | grep -v '^_' 2> /dev/null)

for script in ${(f)LEGACY_SCRIPTS}; do
  [[ -z "$script" ]] && continue
  echo "$c[info]running legacy cleanup$c[reset] $script"
  if is not executable "$LEGACY_DIR/$script"; then
    echo "$c[warn]warning:$c[reset] $script is not executable, making it executable"
    chmod +x "$LEGACY_DIR/$script"
  fi

  "$LEGACY_DIR/$script"

  if is equal "$?" "0"; then
    echo "$c[success]succesfully ran$c[reset] $script"
  else
    echo "$c[error]failed$c[reset] $script"
    exit 1
  fi
  echo ""
  echo ""
done

SCRIPTS=$(ls -1 $INSTALLER_DIR | grep -v '.DS_Store' | grep -v '^_' 2> /dev/null)

for script in ${(f)SCRIPTS}; do
  [[ -z "$script" ]] && continue
  echo "$c[info]running installer$c[reset] $script"
  if is not executable "$INSTALLER_DIR/$script"; then
    echo "$c[warn]warning:$c[reset] $script is not executable, making it executable"
    chmod +x "$INSTALLER_DIR/$script"
  fi

  "$INSTALLER_DIR/$script"

  if is equal "$?" "0"; then
    echo "$c[success]succesfully ran$c[reset] $script"
  else
    echo "$c[error]failed$c[reset] $script"
    exit 1
  fi
  echo ""
  echo ""
done
