#!/usr/bin/env bash

if ! command -v tmux &> /dev/null
then
    echo "tmux could not be found, installing..."
    if [[ "$OSTYPE" == "linux-gnu"* ]]; then
        sudo apt-get update
        sudo apt-get install -y tmux
    elif [[ "$OSTYPE" == "darwin"* ]]; then
        brew install tmux
    else
        echo "Unsupported OS. Please install tmux manually."
        exit 1
    fi
else
    echo "tmux is installed"
fi

echo ""
echo "Linking tmux.conf to home directory..."

if [ "$CUSTOM_DIR" == "" ]; then
  echo '$CUSTOM_DIR is not set, cannot install tmu config'
  exit 1
fi

TMUX_PLUGIN_DIR=$HOME/.tmux/plugins
if [ ! -d "$TMUX_PLUGIN_DIR" ]; then
  mkdir -p $TMUX_PLUGIN_DIR
fi

if [ ! -d "$TMUX_PLUGIN_DIR/tpm" ]; then
  echo "Installing tmux plugin manager..."
  git clone https://github.com/tmux-plugins/tpm $TMUX_PLUGIN_DIR/tpm
  echo "tmux plugin manager installed"
else
  echo "tmux plugin manager already installed"
fi

stub="
# Source the custom tmux conf
source $CUSTOM_DIR/tmux.conf

# reload config file (change file location to your the tmux.conf you want to use)
bind -n C-M-r source-file $CUSTOM_DIR/tmux.conf
"

echo "$stub" > ~/.tmux.conf

echo "linked config"
echo ""
echo "Install new plugins with prefix + I (capital i) inside tmux"
echo "Cleanup old plugins with prefix + alt + u inside tmux"
echo "use Ctrl+Meta+r to reload tmux config"