#!/usr/bin/env zsh

source $CUSTOM_DIR/functions/is

DEST_VIMRC=$HOME/.vimrc

if is not available vim; then
  echo "Installing vim via package manager"
  if is osx; then
    brew install vim
  elif is arch; then
    sudo pacman -S gvim xsel
  elif is linux; then
    sudo apt install vim-gtk3 xsel
  fi
fi

if is existing $DEST_VIMRC; then
  echo "Removing existing .vimrc"
  rm $DEST_VIMRC
fi


echo "Linking .vimrc"

ln -s $CUSTOM_DIR/.vimrc $DEST_VIMRC

echo "installed vim, open it to install plugins with :PlugInstall"
