#!/usr/bin/env zsh

source $CUSTOM_DIR/functions/is

SOURCE_DIR=${0:a:h}/bin
DEST_DIR=/usr/local/bin

if is not linux; then
  echo "install-bin is only for linux"
  exit 1
fi

echo "Installing bin scripts from $SOURCE_DIR to $DEST_DIR"

for script in $SOURCE_DIR/*; do
  name=$(basename $script)
  dest=$DEST_DIR/$name

  if [[ -h $dest ]]; then
    rm $dest
  fi

  sudo ln -s $script $dest
  sudo chmod +x $script
  echo "  linked $name"
done

echo "Done."
