#!/usr/bin/env zsh

SOURCE_DIR=${0:a:h}
CONFIG_DEST="$HOME/.config/micro"

MICRO_BIN="/usr/local/bin/micro"

source "$SOURCE_DIR/functions/is"

echo "Preparing to uninstall micro setup"
echo "Config directory: $CONFIG_DEST"

if [[ -d "$CONFIG_DEST" ]]; then
  echo "Found micro config directory at $CONFIG_DEST, removing it"
  echo "Removing micro config directory at $CONFIG_DEST"
  rm -rf "$CONFIG_DEST"
else
  echo "Config directory does not exist, skipping"
fi

if [[ -x "$MICRO_BIN" ]]; then
  echo "Found micro executable at $MICRO_BIN, removing it"
  sudo rm "$MICRO_BIN"
  echo "Removed $MICRO_BIN"
else
  echo "No executable found at $MICRO_BIN, skipping binary removal"
fi
