#!/usr/bin/env zsh

source "${0:a:h}/installers/_stub"

UPDATER_DIR="$REPO_DIR/updaters"

SCRIPTS=$(ls -1 "$UPDATER_DIR" | grep -v '.DS_Store' | grep -v '^_' 2> /dev/null)

for script in ${(f)SCRIPTS}; do
  [[ -z "$script" ]] && continue
  echo "$c[info]running updater:$c[reset] $script"
  if is not executable "$UPDATER_DIR/$script"; then
    echo "$c[warn]warning:$c[reset] $script is not executable, fixing"
    chmod +x "$UPDATER_DIR/$script"
  fi

  "$UPDATER_DIR/$script"

  if is equal "$?" "0"; then
    echo "$c[success]success:$c[reset] $script complete"
  else
    echo "$c[error]error:$c[reset] $script failed"
    exit 1
  fi

  echo ""
  echo ""
done
