#!/usr/bin/env zsh

SOURCE_DIR="${PWD}/snippets"
OSX_DIR="$HOME/Library/Application Support/Code/User/snippets"

# Install VSCode Snippets
if is osx; then
  echo "installing to $OSX_DIR"
  if is existing "$OSX_DIR" || is symlink "$OSX_DIR"; then
    echo "snippets directory already exists, removing"
    rm -rf "$OSX_DIR"
  fi

  echo "linking $SOURCE_DIR to $OSX_DIR"
  sudo ln -s $SOURCE_DIR "$OSX_DIR"
fi
