#!/usr/bin/env zsh

if [[ -z "$CHEATSHEET_DIR" ]]; then
  echo "CHEATSHEET_DIR not set, set it before running this script"
  exit 1
fi

# if glow doesn't exist exit 1
if ! command -v glow &> /dev/null; then
  echo "glow could not be found, please install it before running this script"
  exit 1
fi

if [[ "$1" != "" ]]; then
  # check if the file exists in the CHEATSHEET_DIR, if it does, open it with glow, if it doesn't, print an error message
  if [[ -f "$CHEATSHEET_DIR/$1.md" ]]; then
    OTHER_ARGS=("${(@)argv[2,-1]}")
    if [[ ${#OTHER_ARGS} -gt 0 ]]; then
      glow "$CHEATSHEET_DIR/$1.md" "${OTHER_ARGS[@]}"
    else
      glow "$CHEATSHEET_DIR/$1.md"
    fi
  else
    glow "$CHEATSHEET_DIR" "$@"
  fi
else
  glow "$CHEATSHEET_DIR" "$@"
fi