#!/usr/bin/env zsh

source "${0:a:h}/_stub"

check-or-load install-link

DEST_DIR=$HOME/.custom
DEST_ZSHRC=$HOME/.zshrc
DEST_ZSHENV=$HOME/.zshenv

install-link $REPO_DIR $DEST_DIR
install-link $REPO_DIR/.zshrc $DEST_ZSHRC
install-link $REPO_DIR/.zshenv $DEST_ZSHENV
install-link $REPO_DIR/configs/python/.default-python-packages $HOME/.default-python-packages

echo "$c[success]zshconfig install complete$c[reset]"