#!/usr/bin/env zsh

INSTALL_SCRIPT_URL=https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh

source "${0:a:h}/_stub"

if is not osx; then
  echo "$c[info]skipping:$c[reset] homebrew is macos only"
  exit 0
fi

if is available brew; then
  echo "$c[info]skipping:$c[reset] homebrew already installed"
  exit 0
fi

echo "$c[info]installing:$c[reset] homebrew"
/bin/bash -c "$(curl -fsSL $INSTALL_SCRIPT_URL)"

if is not equal "$?" "0"; then
  echo "$c[error]error:$c[reset] homebrew install failed"
  exit 1
fi

echo "$c[success]success:$c[reset] homebrew installed"
