#!/usr/bin/env zsh

source "${0:a:h}/_stub"

check-or-load install-release

if is debian; then
  install-release bat || exit 1
  exit 0
fi

if is available bat; then
  echo "$c[info]skipping:$c[reset] bat already installed"
  exit 0
fi

echo "$c[info]installing:$c[reset] bat via homebrew"
if brew install bat; then
  echo "$c[success]success:$c[reset] bat installed"
  exit 0
fi

echo "$c[error]error:$c[reset] homebrew install failed"
echo "$c[info]install instructions:$c[reset] https://github.com/sharkdp/bat"
exit 1
