#!/usr/bin/env zsh

GIT_REPO="git@github.com:jamescodesthings/cheatsheets.git"

source "${0:a:h}/_stub"

check-or-load get-hostname

if is empty "$CHEATSHEET_DIR"; then
  echo "$c[warn]warning:$c[reset] CHEATSHEET_DIR not set, searching for a default location"
  if is dir "$HOME/projects/personal"; then
    export CHEATSHEET_DIR="$HOME/projects/personal/cheatsheets"
    echo "$c[info]info:$c[reset] will use $CHEATSHEET_DIR"
  elif is dir "$HOME/projects"; then
    export CHEATSHEET_DIR="$HOME/projects/cheatsheets"
    echo "$c[info]info:$c[reset] will use $CHEATSHEET_DIR"
  else
    echo "$c[error]error:$c[reset] CHEATSHEET_DIR not set and no projects directory found"
    echo "set $c[em]CHEATSHEET_DIR$c[reset] in your env file before running this installer"
    exit 1
  fi
fi

HOSTNAME=$(get-hostname)
ENV_FILE="$REPO_DIR/env.$HOSTNAME.zsh"

if is not dir "$CHEATSHEET_DIR"; then
  echo "$c[info]cloning:$c[reset] cheatsheets to $CHEATSHEET_DIR"
  git clone "$GIT_REPO" "$CHEATSHEET_DIR"
  if is not equal "$?" "0"; then
    echo "$c[error]error:$c[reset] git clone failed"
    exit 1
  fi
  echo "$c[success]success:$c[reset] cheatsheets cloned to $CHEATSHEET_DIR"
else
  echo "$c[info]updating:$c[reset] cheatsheets at $CHEATSHEET_DIR"
  git -C "$CHEATSHEET_DIR" pull
fi

if is not file "$ENV_FILE"; then
  echo "$c[error]error:$c[reset] environment file not found at $ENV_FILE"
  echo "create $c[em]env.$HOSTNAME.zsh$c[reset] and add CHEATSHEET_DIR before running this installer"
  exit 1
fi

if ! grep -q "CHEATSHEET_DIR" "$ENV_FILE"; then
  echo "$c[info]updating:$c[reset] adding CHEATSHEET_DIR to $ENV_FILE"
  echo "\n\nexport CHEATSHEET_DIR=\"$CHEATSHEET_DIR\"\n" >> "$ENV_FILE"
fi

if is not available "glow"; then
  echo "$c[info]installing:$c[reset] glow"
  if is osx; then
    brew install glow
    if is not equal "$?" "0"; then
      echo "$c[error]error:$c[reset] glow install failed"
      exit 1
    fi
  elif is linux; then
    sudo apt update && sudo apt install -y glow
    if is not equal "$?" "0"; then
      echo "$c[warn]warning:$c[reset] apt install failed"
      echo "$c[info]install instructions:$c[reset] https://github.com/charmbracelet/glow"
      exit 1
    fi
  else
    echo "$c[error]error:$c[reset] unsupported os"
    echo "$c[info]install instructions:$c[reset] https://github.com/charmbracelet/glow"
    exit 1
  fi
  echo "$c[success]success:$c[reset] glow installed"
fi

echo "$c[success]success:$c[reset] cheatsheets install complete"
