#!/usr/bin/env zsh

source "${0:a:h}/_stub"

check-or-load install-release

if is debian; then
  install-release eza || exit 1
  exit 0
fi

if is available eza; then
  echo "$c[info]skipping:$c[reset] eza already installed"
  exit 0
fi

echo "$c[info]installing:$c[reset] eza via homebrew"
if brew install eza; then
  echo "$c[success]success:$c[reset] eza installed"
  exit 0
fi

echo "$c[error]error:$c[reset] homebrew install failed"
echo "$c[info]install instructions:$c[reset] https://github.com/eza-community/eza"
exit 1
