#!/usr/bin/env zsh

source "${0:a:h}/_stub"

check-or-load install-release

if is debian; then
  install-release glow || exit 1
  exit 0
fi

if is available glow; then
  echo "$c[info]skipping:$c[reset] glow already installed"
  exit 0
fi

echo "$c[info]installing:$c[reset] glow via homebrew"
if brew install glow; then
  echo "$c[success]success:$c[reset] glow installed"
  exit 0
fi

echo "$c[error]error:$c[reset] homebrew install failed"
echo "$c[info]install instructions:$c[reset] https://github.com/charmbracelet/glow"
exit 1
