#!/usr/bin/env zsh

source "${0:a:h}/_stub"

if is debian; then
  echo "$c[info]skipping:$c[reset] httpie is installed by 02-apt-base on Debian"
  exit 0
fi

if is available http; then
  echo "$c[info]skipping:$c[reset] httpie already installed"
  exit 0
fi

echo "$c[info]installing:$c[reset] httpie via homebrew"
if brew install httpie; then
  echo "$c[success]success:$c[reset] httpie installed"
  exit 0
fi

echo "$c[error]error:$c[reset] homebrew install failed"
exit 1
