#!/usr/bin/env zsh

source "${0:a:h}/_stub"

check-or-load install-link

DEST_DEFAULT_CONFIG=/etc/keyd/default.conf

if is not equal "$(get-hostname)" "ubuntu"; then
  echo "$c[info]Skipping:$c[reset] keyd is only for linux"
  exit 0
fi


if is not available keyd; then
  echo "Need to install keyd from here: https://github.com/rvaiya/keyd"
  exit 1
fi

echo "$c[info]installing$c[reset] ubuntu pgup/pgdn config"

install-link $REPO_DIR/configs/keyd/default.config $DEST_DEFAULT_CONFIG

sudo keyd reload

echo "$c[success]success:$c[reset] keyd config installed$c[reset]"
