#!/usr/bin/env zsh

source "${0:a:h}/_stub"

check-or-load install-link

if is tty; then
  echo "$c[info]skipping:$c[reset] kitty is a terminal emulator and cannot be installed from a terminal session"
  exit 0
fi

INSTALL_SCRIPT_SOURCE="https://sw.kovidgoyal.net/kitty/installer.sh"
CONFIG_SOURCE="$REPO_DIR/configs/kitty"

OSX_INSTALL_LOCATION="/Applications/kitty.app"
LINUX_INSTALL_LOCATION="$HOME/.local/kitty.app"

OSX_CONFIG_DEST="$HOME/Library/Preferences/kitty"
LINUX_CONFIG_DEST="$HOME/.config/kitty"

if is not available curl; then
  echo "$c[error]failed:$c[reset] curl is required to install kitty, please install it and try again"
  exit 1
fi

if is available kitty || is existing "$OSX_INSTALL_LOCATION" || is dir "$LINUX_INSTALL_LOCATION"; then
  echo "$c[info]updating:$c[reset] kitty is already installed, updating"
else
  echo "$c[info]installing:$c[reset] kitty from $INSTALL_SCRIPT_SOURCE"
fi

curl -fsSL "$INSTALL_SCRIPT_SOURCE" | sh
echo "$c[success]success:$c[reset] kitty installed"

if is linux && is dir "$LINUX_INSTALL_LOCATION"; then
  ln -sf ~/.local/kitty.app/bin/kitty ~/.local/kitty.app/bin/kitten ~/.local/bin/
  cp ~/.local/kitty.app/share/applications/kitty.desktop ~/.local/share/applications/
  cp ~/.local/kitty.app/share/applications/kitty-open.desktop ~/.local/share/applications/
  sed -i "s|Icon=kitty|Icon=$(readlink -f ~)/.local/kitty.app/share/icons/hicolor/256x256/apps/kitty.png|g" ~/.local/share/applications/kitty*.desktop
  sed -i "s|Exec=kitty|Exec=$(readlink -f ~)/.local/kitty.app/bin/kitty|g" ~/.local/share/applications/kitty*.desktop
  echo 'kitty.desktop' > ~/.config/xdg-terminals.list
fi

if is osx; then
  CONFIG_DEST="$OSX_CONFIG_DEST"
else
  CONFIG_DEST="$LINUX_CONFIG_DEST"
fi

if is not dir "$CONFIG_DEST"; then
  echo "$c[info]creating:$c[reset] kitty config directory at $CONFIG_DEST"
  mkdir -p "$CONFIG_DEST"
else
  echo "$c[info]skipping:$c[reset] kitty config directory already exists at $CONFIG_DEST"
fi

install-link "$CONFIG_SOURCE/kitty.conf" "$CONFIG_DEST/kitty.conf"
install-link "$CONFIG_SOURCE/current-theme.conf" "$CONFIG_DEST/current-theme.conf"
install-box-config "$CONFIG_SOURCE/overrides.conf" "$CONFIG_DEST/overrides.conf"