#!/usr/bin/env zsh

source "${0:a:h}/_stub"

check-or-load install-link

if is tty; then
  echo "$c[info]skipping:$c[reset] streamdeck-binaries cannot be installed from a terminal session"
  exit 0
fi

if is not equal "$(get-hostname)" "ubuntu"; then
  echo "$c[warn]skipping: $c[reset]streamdeck-binaries is only for linux"
  exit 0
fi

DEST_DIR=/usr/local/bin
echo "$c[info]installing:$c[reset] streamdeck bin scripts from $REPO_DIR/bin to $DEST_DIR"
for script in $REPO_DIR/bin/*; do
  name=$(basename $script)
  dest=$DEST_DIR/$name

  install-link "$script" "$dest" || exit 1
  sudo chmod +x "$dest"
done

echo "$c[success]success: $c[reset]streamdeck bin scripts install complete"
