#!/usr/bin/env zsh

source "${0:a:h}/_stub"

check-or-load install-link

if is not available subl; then
  if is osx; then
    echo "$c[info]installing:$c[reset] sublime text via homebrew"
    brew install --cask sublime-text
    if is not equal "$?" "0"; then
      echo "$c[error]error:$c[reset] homebrew install failed"
      echo "$c[info]install instructions:$c[reset] https://www.sublimetext.com/docs/linux_repositories.html"
      exit 1
    fi
  elif is linux; then
    echo "$c[info]installing:$c[reset] sublime text via apt"
    wget -qO - https://download.sublimetext.com/sublimehq-pub.gpg | sudo tee /etc/apt/keyrings/sublimehq-pub.asc > /dev/null
    echo -e 'Types: deb\nURIs: https://download.sublimetext.com/\nSuites: apt/stable/\nSigned-By: /etc/apt/keyrings/sublimehq-pub.asc' | sudo tee /etc/apt/sources.list.d/sublime-text.sources > /dev/null
    sudo apt-get update
    sudo apt-get install -y sublime-text
    if is not equal "$?" "0"; then
      echo "$c[error]error:$c[reset] apt install failed"
      echo "$c[info]install instructions:$c[reset] https://www.sublimetext.com/docs/linux_repositories.html"
      exit 1
    fi
  else
    echo "$c[error]error:$c[reset] unsupported os"
    echo "$c[info]install instructions:$c[reset] https://www.sublimetext.com/docs/linux_repositories.html"
    exit 1
  fi
else
  echo "$c[info]skipping:$c[reset] sublime text already installed"
fi

CONFIG_DIR="$REPO_DIR/configs/sublime"

OSX_DIR="$HOME/Library/Application Support/Sublime Text/Packages/User"
LINUX_DIR="$HOME/.config/sublime-text/Packages/User"

DEST_DIR=""

if is osx; then
  DEST_DIR="$OSX_DIR"
elif is linux; then
  DEST_DIR="$LINUX_DIR"
else
  echo "Could not identify system, update ./installers/sublime"
  exit 1
fi

mkdir -p "$DEST_DIR"

install-link "$CONFIG_DIR/Preferences.sublime-settings" "$DEST_DIR/Preferences.sublime-settings"
install-link "$CONFIG_DIR/Default.sublime-mousemap"     "$DEST_DIR/Default.sublime-mousemap"
install-link "$CONFIG_DIR/Default.sublime-keymap"       "$DEST_DIR/Default.sublime-keymap"

if is linux; then
  install-link "$CONFIG_DIR/Default (Linux).sublime-keymap" "$DEST_DIR/Default (Linux).sublime-keymap"
fi

install-link "$CONFIG_DIR/snippets" "$DEST_DIR/snippets"
