#!/usr/bin/env zsh

source "${0:a:h}/_stub".

if is available fuck; then
  echo "'fuck' already installed"
  exit 0
fi

if is available brew; then
  brew install thefuck
  if is equal "$?" "0"; then
    echo "thefuck installed"
    eval $(thefuck --alias)
    exit 0
  else
    echo "Failed to install 'thefuck' using Homebrew"
    echo "Check: https://github.com/nvbn/thefuck#installation"
    exit 1
  fi
fi

if is available pip; then
  pip install thefuck --user
    if is equal "$?" "0"; then
    echo "thefuck installed"
    eval $(thefuck --alias)
    exit 0
  else
    echo "Failed to install 'thefuck' using pip"
    echo "Check: https://github.com/nvbn/thefuck#installation"
    exit 1
  fi
fi

echo "No installation methods found"
echo "Check: https://github.com/nvbn/thefuck#installation"
exit 1