#!/usr/bin/env zsh

source "${0:a:h}/_stub"

check-or-load install-release

if is debian; then
  install-release tldr || exit 1
  exit 0
fi

if is available tldr; then
  echo "$c[info]skipping:$c[reset] tldr already installed"
  exit 0
fi

echo "$c[info]installing:$c[reset] tldr via homebrew"
if brew install tlrc; then
  echo "$c[success]success:$c[reset] tldr installed"
  exit 0
fi

echo "$c[error]error:$c[reset] homebrew install failed"
echo "$c[info]install instructions:$c[reset] https://github.com/tldr-pages/tlrc"
exit 1
