#!/usr/bin/env zsh

source "${0:a:h}/_stub"

check-or-load install-link
check-or-load install-link

CONFIG_DIR="$REPO_DIR/configs/vscode"

OSX_DIR="$HOME/Library/Application Support/Code/User"
LINUX_DIR="$HOME/.config/Code/User"

DEST_DIR=""
SETTINGS_SUFFIX=""

if is tty; then
  echo "$c[info]skipping:$c[reset] vscode isn't available on a tty"
  exit 0
fi

if is osx; then
  DEST_DIR="$OSX_DIR"
fi

if is linux; then
  DEST_DIR="$LINUX_DIR"
fi

if [ "$DEST_DIR" = "" ]; then
  echo "Could not identify system, update ./install"
  exit 1
fi

install-link "$CONFIG_DIR/snippets" "$DEST_DIR/snippets"
install-box-config "$CONFIG_DIR/settings.json" "$DEST_DIR/settings.json"
install-box-config "$CONFIG_DIR/keybindings.json" "$DEST_DIR/keybindings.json"
