#pragma once
#define PROJECT_VERSION_MAJOR @$PROJECT_NAME_TITLE_VERSION_MAJOR@
#define PROJECT_VERSION_MINOR @$PROJECT_NAME_TITLE_VERSION_MINOR@
#define PROJECT_VERSION_PATCH @$PROJECT_NAME_TITLE_VERSION_PATCH@
