#!/usr/bin/env zsh
source "${0:a:h}/_stub"

if is not available pacman; then
  echo "$c[info]skipping:$c[reset] pacman not available"
  exit 0
fi

echo "$c[info]updating:$c[reset] arch packages"
sudo pacman -Syu
if is not equal "$?" "0"; then
  echo "$c[error]error:$c[reset] pacman update failed"
  exit 1
fi

echo "$c[success]success:$c[reset] arch packages updated"
