#!/usr/bin/env zsh
source "${0:a:h}/_stub"

if is not available xcodes; then
  echo "$c[info]skipping:$c[reset] xcodes not installed"
  exit 0
fi

echo "$c[info]updating:$c[reset] xcodes"
xcodes update
if is not equal "$?" "0"; then
  echo "$c[error]error:$c[reset] xcodes update failed"
  exit 1
fi

echo "$c[success]success:$c[reset] xcodes updated"
